name: easy_form_kit
description: A set of widgets for processing form field data in one common handler. Convenient for saving data to a database, sending via API, etc.
version: 5.0.0
author: Andy Chentsov <chentsov@gmail.com>
homepage: https://github.com/andyduke/easy_form_kit/tree/master/package
repository: https://github.com/andyduke/easy_form_kit
issue_tracker: https://github.com/andyduke/easy_form_kit/issues

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
